<?php if (isset($message)) :
echo $message;
endif; ?>
<div>
    <a href="/users/new">Новый пользователь</a>
</div>
<form method="get">
  <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
  <input type="submit" value="Search" />
</form>
<hr>
<?php foreach ($users as $user): ?>
<div>
    <?= htmlspecialchars($user['name']) ?>
    <a href="/users/<?= htmlspecialchars($user['id'])?>">Посмотреть</a>
    <a href="/users/<?= htmlspecialchars($user['id'])?>/edit">Изменить</a>
    <form method="post" action="/users/<?= htmlspecialchars($user['id'])?>/del">
        <input type="hidden" name="_METHOD" value="DELETE">
        <input type="submit" value="Delete">
    </form>
</div>
<?php endforeach; ?>
